### ISSUE TITLE
After upgrading to 2.0 beta - extracted Chunk.isInitial is not a function

### ISSUE THREAD

**Issue by EdwardDrapkin** [webpack/extract-text-webpack-plugin#214]
Hey there,

I recently upgraded to ETP beta-2 to give it a whirl and things started breaking.

This was my config before

    const etp = new ExtractTextPlugin('css/temp/[name].css?[hash]-[chunkhash]-[contenthash]-[name]', {
        allChunks: true
    });

    loaders.push({
        test: /\.s?css$/,
        loader: etp.extract('style', [
            `css-loader?modules&importLoaders=1&localIdentName=${cssModuleFormat}!sass-loader?config=sassLoader`
        ])
    });

    plugins.push(etp);

And my new config, after upgrading:

    const etp = new ExtractTextPlugin({
        filename: 'css/temp/[name].css?[hash]-[chunkhash]-[contenthash]-[name]',
        allChunks: true
    });

    loaders.push({
        test: /\.s?css$/,
        loader: etp.extract({
            notExtractLoader: 'style',
            loader: `css-loader?modules&importLoaders=1&localIdentName=${cssModuleFormat}!sass-loader?config=sassLoader`
        })
    });

Here's the stack trace:

    TypeError: extractedChunk.isInitial is not a function
        at ExtractTextPlugin.<anonymous> (/var/www/projects/hsb-app/proj/node_modules/extract-text-webpack-plugin/index.js:280:24)
        at Array.forEach (native)
        at ExtractTextPlugin.<anonymous> (/var/www/projects/hsb-app/proj/node_modules/extract-text-webpack-plugin/index.js:279:21)
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:52:16
        at Object.async.forEachOf.async.eachOf (/var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:236:30)
        at Object.async.forEach.async.each (/var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:209:22)
        at ExtractTextPlugin.<anonymous> (/var/www/projects/hsb-app/proj/node_modules/extract-text-webpack-plugin/index.js:243:10)
        at Compilation.applyPluginsAsync (/var/www/projects/hsb-app/proj/node_modules/tapable/lib/Tapable.js:85:13)
        at Compilation.seal (/var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:519:7)
        at Compiler.<anonymous> (/var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compiler.js:431:15)
        at /var/www/projects/hsb-app/proj/node_modules/tapable/lib/Tapable.js:152:11
        at Compilation.<anonymous> (/var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:430:10)
        at /var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:405:12
        at /var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:320:10
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:52:16
        at done (/var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:246:17)
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:44:16
        at /var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:320:10
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:52:16
        at done (/var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:246:17)
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:44:16
        at /var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:320:10
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:52:16
        at done (/var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:246:17)
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:44:16
        at /var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:320:10
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:52:16
        at done (/var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:246:17)
        at /var/www/projects/hsb-app/proj/node_modules/async/lib/async.js:44:16
        at errorAndCallback (/var/www/projects/hsb-app/proj/node_modules/webpack/lib/Compilation.js:196:5)

It's probably important that I'm using webpack 2 beta with System.import() code splitting with es6 native modules.

**Comment by EdwardDrapkin** [comment]
It looks like the webpack API may have changed. 

I replaced all invocations of `isInitial()` with accessing the `initial` property (e.g. `if(extractedChunk.isInitial())` => `if(extractedChunk.initial)` and everything works as expected.  

I'll get a pull request open here in an hour or two.

**Comment by EdwardDrapkin** [comment]
Ah nevermind, my webpack beta was ancient.  Sorry forwasting your time.

**Comment by laggingreflex** [comment]
Was having the same issue, upgrading webpack solved it. 

Peer dependency should be updated to 2.1.0-beta.19

**Comment by robwise** [comment]
same issue, same solution

**Comment by Roam-Cooper** [comment]
👍

**Comment by tpina** [comment]
Same here! Webpack upgrade and fixed it.

**Comment by happyvig** [comment]
Hi.,

I am using **Node v6.2.2** & **Angular 2.0.0** along with
```
"Webpack" : "^2.1.0-beta.17",
"extract-text-webpack-plugin": "^2.0.0-beta.0".
"typescript": "~2.0.2",
```

It throws error as 
```
 iterator(object[key], key, only_once(done));
 ^
TypeError: chunk.isInitial is not a function
```

I have tried using extract-text-webpack-plugin : 2.0.0-beta.1 & 2 versions as well.
Still the same issue.

If this fixed in any of the latest beta versions ?

**Comment by dben** [comment]
The issue reappears in webpack 2.1.0-beta.23 - downgrading to 2.1.0-beta.22 should solve it temporarily.

**Comment by andywer** [comment]
@sokra Any idea why this issue reappeared with webpack 2.1.0-beta.23? Noticed it's broken, too.

**Comment by jony89** [comment]
same issue here, occurs with webpack 2.2.1

**Comment by zabojad** [comment]
Idem, I'm having this with Webpack 2.2.1 as well

**Comment by jony89** [comment]
@zabojad see #461

**Comment by zabojad** [comment]
Great, thank you @jony89 !

**Comment by breneser** [comment]
I started getting this exact error again today with a React app I created using https://github.com/facebookincubator/create-react-app

Has something just got updated ?
